//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediSync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gu-sxd7e-025\\AX;Initial Catalog=MicrosoftDynamicsAX;Persist Security " +
            "Info=True;User ID=gu51;Password=WeberVPN")]
        public string AXConnString {
            get {
                return ((string)(this["AXConnString"]));
            }
            set {
                this["AXConnString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gu51")]
        public string DbUser {
            get {
                return ((string)(this["DbUser"]));
            }
            set {
                this["DbUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WeberVPN")]
        public string DbPass {
            get {
                return ((string)(this["DbPass"]));
            }
            set {
                this["DbPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gu-sxd7e-019/Medistim/")]
        public string CrmProdUrl {
            get {
                return ((string)(this["CrmProdUrl"]));
            }
            set {
                this["CrmProdUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultCrmServerChoice {
            get {
                return ((string)(this["DefaultCrmServerChoice"]));
            }
            set {
                this["DefaultCrmServerChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"					SELECT 
					   [msus_medisyncId]
					  ,[CreatedOn]
					  ,[CreatedBy]
					  ,[ModifiedOn]
					  ,[ModifiedBy]
					  ,[CreatedOnBehalfBy]
					  ,[ModifiedOnBehalfBy]
					  ,[OwnerId]
					  ,[OwnerIdType]
					  ,[OwningBusinessUnit]
					  ,[statecode]
					  ,[statuscode]
					  ,[VersionNumber]
					  ,[ImportSequenceNumber]
					  ,[OverriddenCreatedOn]
					  ,[TimeZoneRuleVersionNumber]
					  ,[UTCConversionTimeZoneCode]
					  ,[msus_name]
					  ,[msus_Enabled]
					  ,[msus_Interval]
					  ,[msus_Lastrun]
					  ,[msus_LastRunSuccessful]
					  ,[msus_Priority]
					  ,[msus_Runasuser]
					  ,[msus_Runasuserpassword]
					  ,[new_Targetentity]
                                                                                  ,[msus_target_entity_alias]
					  ,[new_AXjoincolumn]
					  ,[new_CRMjoincolumn]
					  ,[new_AXTargetCols]
					  ,[new_CRMTargetCols]
					  ,[new_CRMJoinTable]
					  ,[new_AXJoinTable]
					  ,[msus_lastrun_utc]
                      ,[msus_FromClause]
					  ,[msus_axdatecolumn]
					FROM [msus_medisyncBase]")]
        public string GetJobListQuery {
            get {
                return ((string)(this["GetJobListQuery"]));
            }
            set {
                this["GetJobListQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=gu-sxd7e-025\\CRM;Initial Catalog=Medistim_MSCRM;Persist Security Info" +
            "=True;User ID=gu51;Password=WeberVPN")]
        public string CRMConnString {
            get {
                return ((string)(this["CRMConnString"]));
            }
            set {
                this["CRMConnString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[CRM].Medistim_MSCRM.[dbo]")]
        public string CrmDbQualifyingPrefix {
            get {
                return ((string)(this["CrmDbQualifyingPrefix"]));
            }
            set {
                this["CrmDbQualifyingPrefix"] = value;
            }
        }
    }
}
